apiVersion: v1
kind: Pod
metadata:
    name: init-container
    labels:
      app: nginx-init
spec: 
    containers:
      - name: nginx
        image: nginx
        ports: 
           - containerPort: 80 
        volumeMounts: 
           - name: shared
             mountPath: /usr/share/nginx/html
    initContainers:
      - name: busybox
        image: busybox
        command: ["/bin/sh"]
        args: ["-c","echo '<html><h2>Hi I am from Inint container</h2></html>' >> /work-dir/index.html"]
        volumeMounts:
           - name: shared
             mountPath: "/work-dir"
    dnsPolicy: Default       
    volumes: 
      - name: shared
        emptyDir: {}

--- 

apiVersion: v1
kind: Service
metadata:
    name: init-container-service
spec: 
   type: NodePort
   ports:
   - port: 80
     protocol: TCP
   selector: 
     app: nginx-init
