apiVersion: v1
kind: Pod
metadata:
    name: sidecar-container
    labels:
      app: nginx-sidecar
spec: 
    containers:
      - name: nginx
        image: nginx
        ports: 
           - containerPort: 80 
        volumeMounts: 
           - name: shared-logs
             mountPath: /var/log/nginx
             
      - name: sidecar-container-as-adaptor
        image: busybox
        command: ["/bin/sh"]
        args: ["-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 10; done"]
        volumeMounts:
           - name: shared-logs
             mountPath: "/var/log/nginx"
    volumes: 
      - name: shared-logs
        emptyDir: {}

