apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
      app: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: harshajain/k8s_ip:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
