apiVersion: v1 
kind: Service
metadata: 
    name: svc-headless
spec:
    clusterIP: None     
    selector:
          app: nginx
    ports:
        - name: http 
          port: 30084
          targetPort: 80
