apiVersion: v1 
kind: Service
metadata: 
    name: svc-nodeport
spec:
    type: NodePort     
    selector:
          app: nginx
    ports:
        - name: http 
          nodePort: 30082 
          port: 30080
          targetPort: 80
