apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-stateful
  template:
    metadata:
      labels:
        app: nginx-stateful
    spec:
      containers:
      - name: nginx
        image: harshajain/k8s_ip:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
