apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
   - name: nginx
     image: nginx:1.14.2
     ports:
       - containerPort: 80
     env: 
       - name: DB_URL
         valueFrom: 
            secretKeyRef: 
               name: my-secret
               key: db_url
       - name: DB_PASS
         valueFrom:
            secretKeyRef:
               name: my-secret
               key: db_password
