apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
   - name: nginx
     image: nginx:1.14.2
     ports:
       - containerPort: 80
     env: 
       - name: ENVIRONMENT
         valueFrom: 
            configMapKeyRef: 
               name: my-configmap1
               key: environment
       - name: APP_TYPE
         valueFrom:
            configMapKeyRef:
               name: my-configmap1
               key: app
     volumeMounts:
       - name: config
         mountPath: "/config"
         readOnly: true       
  volumes:
   - name: config
     configMap: 
        name: my-configmap1
        items: 
         - key: "app.properties"
           path: "app.properties"
