apiVersion: v1
kind: PersistentVolume
metadata: 
    name: my-pv
spec:
    storageClassName: local
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 2Gi
    hostPath:
        path: '/home/ubuntu/pv-volume'
