apiVersion: v1
kind: Pod
metadata:
   name: liveness
spec:
   containers:
   - name: liveness
     image: registry.k8s.io/liveness
     args:
      - /server
     livenessProbe:
       httpGet:
         path: /healthz
         port: 8080
         httpHeaders:
         - name: Custom-Header
           value: Awesome
       initialDelaySeconds: 5
       periodSeconds: 3
